name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  unit-tests:
    name: UNIT Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Packages
        run: pip3.10 install -r requirements.txt

      - name: Run unit tests for reservation service
        run: pytest -vs reservation_service/tests/reservation.py

      #- name: Run unit tests for payment service
      #  run: pytest -vs services/payment_service/app/unit_tests/tests.py
      #  
      #- name: Run unit tests for reservation service
      #  run: pytest -vs services/reservation_service/app/unit_tests/tests.py
  
  deploy:
    name: Deploy service on VM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Copy code to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "reservation_service,payment_service,loyalty_service,gateway_service,scripts,v2,docker,docker-compose.yml,requirements.txt,config.yaml,Makefile"
          target: /home/${{ secrets.SSH_USERNAME }}/hotel-booking-system

      - name: Run app on VM
        uses: appleboy/ssh-action@v1.0.0
        env: 
          WAIT_PORTS: 8080,8070,8060,8050
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/hotel-booking-system
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi gateway_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi reservation_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi payment_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi loyalty_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rmi gateway_service
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d
            echo ${{ secrets.SSH_PASSWORD }} | sudo ./scripts/wait-script.sh
  
  api-test:
    name: API Tests
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          run: ./scripts/test-script.sh v2 loyalty_service 8050
        #  env:
        #    VARIANT: v2
        #    SERVICE_NAME: loyalty_service
        #    PORT_NUMBER: 8050
  
      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true
  
   #  - name: Github auto grader mark
   #    uses: Romanow/google-sheet-autograder-marker@v1.0
   #    with:
   #      google_token: ${{secrets.GOOGLE_API_KEY}}
   #      sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
   #      homework_number: 3
   #      user_column: 'D'
   #      column_offset: 'F'
   #      mark: "'+"
   #
  #    - name: Stop containers
  #      if: always()
  #      continue-on-error: true
  #      run: docker compose down -v
